// I7 — the Pi result card variant that shows a *generated* chart on the Analytics
// surface. Renders the spec's ECharts option in the app's chart wrapper, plus the
// natural-language insight and a real PNG export (via the chart instance's
// getDataURL). "Add as card" is a mock confirm for the prototype.

import { useRef } from "react";
import type { ECharts } from "echarts";
import { Sparkle, Download, LayoutGrid } from "lucide-react";
import { EChart } from "@/components/analytics/EChart";
import type { PiChartSpec } from "@/lib/pi-charts";

export function PiChartResult({
  spec,
  onAdd,
  onDismiss,
}: {
  spec: PiChartSpec;
  onAdd: () => void;
  onDismiss: () => void;
}) {
  const chartInst = useRef<ECharts | null>(null);

  const downloadPng = () => {
    const inst = chartInst.current;
    if (!inst) return;
    const url = inst.getDataURL({ type: "png", pixelRatio: 2, backgroundColor: "#ffffff" });
    const a = document.createElement("a");
    a.href = url;
    a.download = `${spec.slug}.png`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  return (
    <div className="space-y-2.5">
      {/* Natural-language answer */}
      <div className="flex items-start gap-2">
        <Sparkle className="mt-0.5 h-3.5 w-3.5 shrink-0 fill-ai text-ai" />
        <p className="text-[13px] leading-relaxed text-foreground">{spec.insight}</p>
      </div>

      {/* Generated chart, framed like an analytics card */}
      <div className="overflow-hidden rounded-xl border border-border bg-card">
        <div className="flex items-center justify-between border-b border-border px-3 py-2">
          <div>
            <h4 className="text-[12.5px] font-semibold leading-tight text-foreground">{spec.title}</h4>
            <p className="text-[10.5px] text-muted-foreground">{spec.sub}</p>
          </div>
          <span className="flex items-center gap-1 rounded-full border border-ai/30 bg-ai/5 px-2 py-0.5 text-[9.5px] font-medium text-ai">
            <Sparkle className="h-2.5 w-2.5 fill-ai" /> Generated by Pi
          </span>
        </div>
        <div className="px-2 py-2">
          <div className="h-[220px] w-full">
            <EChart option={spec.option} instanceRef={chartInst} />
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-1.5">
        <button onClick={onDismiss} className="rounded-md px-2.5 py-1 text-[11.5px] text-muted-foreground hover:text-foreground">
          Dismiss
        </button>
        <button
          onClick={downloadPng}
          className="inline-flex items-center gap-1 rounded-md border border-border px-2.5 py-1 text-[11.5px] font-medium text-foreground hover:bg-accent"
        >
          <Download className="h-3 w-3" /> Download PNG
        </button>
        <button
          onClick={onAdd}
          className="inline-flex items-center gap-1 rounded-md bg-foreground px-2.5 py-1 text-[11.5px] font-medium text-background"
        >
          <LayoutGrid className="h-3 w-3" /> Add as card
        </button>
      </div>
    </div>
  );
}
