#!/usr/bin/env node
/**
 * Seed Cloudflare D1 (local or remote) with the current in-memory workspace.
 *
 * Data sources (all TS modules in src/lib):
 *   - campaigns:   EXAMPLE_CAMPAIGNS       from campaign-examples
 *   - runs:        derived via analytics-data.CAMPAIGNS[*].runs (deriveRun)
 *   - leads:       generateLeads(run, run.kpi.validLeads) per run
 *   - templates:   SEED_TEMPLATES / SEED_SMS_TEMPLATES / SEED_RCS_TEMPLATES
 *   - agents:      AGENT_RECORDS from agent-data
 *   - tools:       TOOLS from tool-registry
 *   - freeform:    SEED_FREEFORM_WORKFLOWS from freeform-types
 *
 * Usage:
 *   npx tsx scripts/seed-d1.mjs                    # emit .sql to stdout
 *   npx tsx scripts/seed-d1.mjs > seed.sql         # capture for wrangler
 *   npx wrangler d1 execute picom-vision --local --file=seed.sql
 *   npx wrangler d1 execute picom-vision --remote --file=seed.sql
 *
 * Emits a single .sql file so the D1 apply is atomic and re-runnable
 * (`INSERT OR REPLACE` everywhere). Reading the TS sources via tsx keeps this
 * script one source-of-truth away from the app code.
 */
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Bring in every seed source. All are pure-data modules; no browser globals.
const { EXAMPLE_CAMPAIGNS } = await import(join(ROOT, "src/lib/campaign-examples.ts"));
const { CAMPAIGNS } = await import(join(ROOT, "src/lib/analytics-data.ts"));
const { generateLeads } = await import(join(ROOT, "src/lib/analytics-leads.ts"));
const { SEED_TEMPLATES } = await import(join(ROOT, "src/lib/waba-templates.ts"));
const { SEED_SMS_TEMPLATES } = await import(join(ROOT, "src/lib/sms-templates.ts"));
const { SEED_RCS_TEMPLATES } = await import(join(ROOT, "src/lib/rcs-templates.ts"));
const { AGENT_RECORDS } = await import(join(ROOT, "src/lib/agent-data.ts"));
const { TOOLS } = await import(join(ROOT, "src/lib/tool-registry.ts"));
const { SEED_FREEFORM_WORKFLOWS } = await import(join(ROOT, "src/lib/freeform-types.ts"));

const now = Date.now();
const out = [];
const push = (s) => out.push(s);
const q = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return `'${String(v).replace(/'/g, "''")}'`;
};

push("-- Auto-generated by scripts/seed-d1.mjs — do not edit by hand.");
push("BEGIN TRANSACTION;");

// ---- Campaigns + nodes + edges ----
push("\n-- Campaigns");
for (const [id, ex] of Object.entries(EXAMPLE_CAMPAIGNS)) {
  const vertical = /^b2b/i.test(ex.name) ? "b2b"
    : /^bfsi/i.test(ex.name) ? "bfsi"
    : /^d2c/i.test(ex.name) ? "d2c"
    : "retail";
  push(
    `INSERT OR REPLACE INTO campaigns (id, name, vertical, status, description, created_at, updated_at) VALUES (${q(id)}, ${q(ex.name)}, ${q(vertical)}, ${q(ex.status)}, NULL, ${q(now)}, ${q(now)});`,
  );
  for (const n of ex.nodes) {
    push(
      `INSERT OR REPLACE INTO campaign_nodes (id, campaign_id, kind, title, subtitle, serial, position_x, position_y, config_json, outputs_json) VALUES (${q(n.id)}, ${q(id)}, ${q(n.data.kind)}, ${q(n.data.title)}, ${q(n.data.subtitle ?? null)}, ${q(n.data.serial ?? null)}, ${q(n.position?.x ?? 0)}, ${q(n.position?.y ?? 0)}, ${q(JSON.stringify(n.data.config ?? {}))}, ${q(JSON.stringify(n.data.outputs ?? []))});`,
    );
  }
  for (const e of ex.edges) {
    push(
      `INSERT OR REPLACE INTO campaign_edges (id, campaign_id, source_id, target_id, source_handle) VALUES (${q(e.id)}, ${q(id)}, ${q(e.source)}, ${q(e.target)}, ${q(e.sourceHandle ?? null)});`,
    );
  }
}

// ---- Runs + per-node metrics + per-edge metrics + leads ----
push("\n-- Runs, node/edge metrics, leads");
for (const camp of CAMPAIGNS) {
  for (const run of camp.runs) {
    push(
      `INSERT OR REPLACE INTO runs (id, campaign_id, code, name, status, run_type, trigger_mode, audience_source, audience_size, total_leads, valid_leads, leads_processed, success_rate, started_at, completed_at) VALUES (${q(run.id)}, ${q(camp.id)}, ${q(run.code)}, ${q(run.name)}, ${q(run.status)}, ${q(run.runType)}, ${q(run.triggerMode ?? "manual")}, ${q(run.audienceSource ?? "csv")}, ${q(run.audience)}, ${q(run.totalLeads)}, ${q(run.kpi.validLeads)}, ${q(run.kpi.leadsProcessed)}, ${q(run.kpi.successRate)}, ${q(now)}, ${q(run.status === "completed" ? now : null)});`,
    );
    for (const n of run.sankey.nodes) {
      push(
        `INSERT OR REPLACE INTO run_node_metrics (run_id, node_id, entered, exited) VALUES (${q(run.id)}, ${q(n.id)}, ${q(n.entered)}, ${q(n.exited)});`,
      );
    }
    for (const e of run.sankey.edges) {
      push(
        `INSERT OR REPLACE INTO run_edge_metrics (run_id, edge_id, source_id, target_id, source_handle, value) VALUES (${q(`${run.id}_${e.source}_${e.target}_${e.sourceHandle ?? "default"}`)}, ${q(run.id)}, ${q(e.source)}, ${q(e.target)}, ${q(e.sourceHandle ?? null)}, ${q(e.value)});`,
      );
    }
    // Seed leads. `generateLeads` returns validLeads-worth of rows.
    const leads = generateLeads(run, run.kpi.validLeads);
    for (const lead of leads) {
      const stageKind = run.sankey.nodes.find((n) => n.id === lead.stageNodeId)?.kind ?? "start";
      push(
        `INSERT OR REPLACE INTO leads (id, run_id, campaign_id, name, phone, email, stage_node_id, stage_kind, channel, status, cost, duration_sec, attributes_json, updated_at) VALUES (${q(`${run.id}_${lead.id}`)}, ${q(run.id)}, ${q(camp.id)}, ${q(lead.name)}, ${q(lead.phone)}, ${q(lead.email)}, ${q(lead.stageNodeId)}, ${q(stageKind)}, ${q(lead.channel ?? null)}, ${q(lead.status ?? null)}, ${q(lead.cost)}, ${q(lead.duration ?? null)}, ${q("{}")}, ${q(now)});`,
      );
    }
  }
}

// ---- Templates ----
push("\n-- WA templates");
for (const t of SEED_TEMPLATES) {
  push(
    `INSERT OR REPLACE INTO wa_templates (id, name, category, language, format, status, created_at, header, body, footer, buttons_json) VALUES (${q(t.id)}, ${q(t.name)}, ${q(t.category)}, ${q(t.language)}, ${q(t.format)}, ${q(t.status)}, ${q(t.createdAt)}, ${q(t.header ?? null)}, ${q(t.body)}, ${q(t.footer ?? null)}, ${q(JSON.stringify(t.buttons ?? []))});`,
  );
}
push("\n-- SMS templates");
for (const t of SEED_SMS_TEMPLATES) {
  push(
    `INSERT OR REPLACE INTO sms_templates (id, name, pe_id, sender_id, category, encoding, body, created_at) VALUES (${q(t.id)}, ${q(t.name)}, ${q(t.peId)}, ${q(t.senderId)}, ${q(t.category)}, ${q(t.encoding)}, ${q(t.body)}, ${q(t.createdAt)});`,
  );
}
push("\n-- RCS templates");
for (const t of SEED_RCS_TEMPLATES) {
  push(
    `INSERT OR REPLACE INTO rcs_templates (id, name, agent_id, kind, body, suggestions_json, created_at) VALUES (${q(t.id)}, ${q(t.name)}, ${q(t.agentId)}, ${q(t.kind ?? "text")}, ${q(t.body ?? "")}, ${q(JSON.stringify(t.suggestions ?? []))}, ${q(t.createdAt)});`,
  );
}

// ---- Agents ----
push("\n-- Agents");
for (const [id, a] of Object.entries(AGENT_RECORDS)) {
  push(
    `INSERT OR REPLACE INTO agents (id, name, type, status, tools_json, master_prompt, knowledge_base, post_call_json, eval_prompt, created_at, updated_at) VALUES (${q(id)}, ${q(a.name)}, ${q(a.type)}, ${q(a.status)}, ${q(JSON.stringify(a.tools))}, ${q(a.masterPrompt)}, ${q(a.knowledgeBase)}, ${q(JSON.stringify(a.postCall))}, ${q(a.evalPrompt ?? null)}, ${q(now)}, ${q(now)});`,
  );
}

// ---- Tools ----
push("\n-- Tools");
for (const t of TOOLS) {
  push(
    `INSERT OR REPLACE INTO tools (handle, description, type, method, url, auth, health, status, inputs_json, outputs_json, created_at, updated_at) VALUES (${q(t.handle)}, ${q(t.description)}, ${q(t.type)}, ${q(t.method)}, ${q(t.url)}, ${q(t.auth)}, ${q(t.health)}, ${q(t.status)}, ${q(JSON.stringify(t.inputs))}, ${q(JSON.stringify(t.outputs))}, ${q(t.createdAt)}, ${q(t.updatedAt)});`,
  );
}

// ---- Freeform workflows ----
push("\n-- Freeform workflows");
for (const w of SEED_FREEFORM_WORKFLOWS) {
  push(
    `INSERT OR REPLACE INTO freeform_workflows (id, name, description, status, locked, locked_at, used_in_campaigns, nodes_json, edges_json, created_at, updated_at) VALUES (${q(w.id)}, ${q(w.name)}, ${q(w.description ?? null)}, ${q(w.status)}, ${q(w.locked ? 1 : 0)}, ${q(w.lockedAt ? Date.parse(w.lockedAt) : null)}, ${q(w.usedInCampaigns ?? 0)}, ${q(JSON.stringify(w.nodes))}, ${q(JSON.stringify(w.edges))}, ${q(Date.parse(w.createdAt))}, ${q(Date.parse(w.lastModified))});`,
  );
}

push("\nCOMMIT;");
process.stdout.write(out.join("\n") + "\n");
