/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ChannelsIndexRouteImport } from './routes/channels.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as ChannelsWhatsappRouteImport } from './routes/channels.whatsapp'
import { Route as ChannelsSmsRouteImport } from './routes/channels.sms'
import { Route as ChannelsRcsRouteImport } from './routes/channels.rcs'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as CampaignsVersionsIdRouteImport } from './routes/campaigns.versions.$id'
import { Route as AgentsToolsNewRouteImport } from './routes/agents.tools.new'
import { Route as ChannelsWhatsappFreeformIdRouteImport } from './routes/channels.whatsapp_.freeform.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelsRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsWhatsappRoute = ChannelsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => ChannelsRoute,
} as any)
const ChannelsSmsRoute = ChannelsSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => ChannelsRoute,
} as any)
const ChannelsRcsRoute = ChannelsRcsRouteImport.update({
  id: '/rcs',
  path: '/rcs',
  getParentRoute: () => ChannelsRoute,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const CampaignsVersionsIdRoute = CampaignsVersionsIdRouteImport.update({
  id: '/versions/$id',
  path: '/versions/$id',
  getParentRoute: () => CampaignsRoute,
} as any)
const AgentsToolsNewRoute = AgentsToolsNewRouteImport.update({
  id: '/tools/new',
  path: '/tools/new',
  getParentRoute: () => AgentsRoute,
} as any)
const ChannelsWhatsappFreeformIdRoute =
  ChannelsWhatsappFreeformIdRouteImport.update({
    id: '/whatsapp_/freeform/$id',
    path: '/whatsapp/freeform/$id',
    getParentRoute: () => ChannelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/channels': typeof ChannelsRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/channels/rcs': typeof ChannelsRcsRoute
  '/channels/sms': typeof ChannelsSmsRoute
  '/channels/whatsapp': typeof ChannelsWhatsappRoute
  '/inbox/$id': typeof InboxIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/agents/tools/new': typeof AgentsToolsNewRoute
  '/campaigns/versions/$id': typeof CampaignsVersionsIdRoute
  '/channels/whatsapp/freeform/$id': typeof ChannelsWhatsappFreeformIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/channels/rcs': typeof ChannelsRcsRoute
  '/channels/sms': typeof ChannelsSmsRoute
  '/channels/whatsapp': typeof ChannelsWhatsappRoute
  '/inbox/$id': typeof InboxIdRoute
  '/agents': typeof AgentsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/agents/tools/new': typeof AgentsToolsNewRoute
  '/campaigns/versions/$id': typeof CampaignsVersionsIdRoute
  '/channels/whatsapp/freeform/$id': typeof ChannelsWhatsappFreeformIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/channels': typeof ChannelsRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/channels/rcs': typeof ChannelsRcsRoute
  '/channels/sms': typeof ChannelsSmsRoute
  '/channels/whatsapp': typeof ChannelsWhatsappRoute
  '/inbox/$id': typeof InboxIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/agents/tools/new': typeof AgentsToolsNewRoute
  '/campaigns/versions/$id': typeof CampaignsVersionsIdRoute
  '/channels/whatsapp_/freeform/$id': typeof ChannelsWhatsappFreeformIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/channels'
    | '/integrations'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/campaigns/$id'
    | '/channels/rcs'
    | '/channels/sms'
    | '/channels/whatsapp'
    | '/inbox/$id'
    | '/agents/'
    | '/campaigns/'
    | '/channels/'
    | '/inbox/'
    | '/integrations/'
    | '/agents/tools/new'
    | '/campaigns/versions/$id'
    | '/channels/whatsapp/freeform/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/campaigns/$id'
    | '/channels/rcs'
    | '/channels/sms'
    | '/channels/whatsapp'
    | '/inbox/$id'
    | '/agents'
    | '/campaigns'
    | '/channels'
    | '/inbox'
    | '/integrations'
    | '/agents/tools/new'
    | '/campaigns/versions/$id'
    | '/channels/whatsapp/freeform/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/channels'
    | '/integrations'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/campaigns/$id'
    | '/channels/rcs'
    | '/channels/sms'
    | '/channels/whatsapp'
    | '/inbox/$id'
    | '/agents/'
    | '/campaigns/'
    | '/channels/'
    | '/inbox/'
    | '/integrations/'
    | '/agents/tools/new'
    | '/campaigns/versions/$id'
    | '/channels/whatsapp_/freeform/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ChannelsRoute: typeof ChannelsRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  InboxIdRoute: typeof InboxIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/whatsapp': {
      id: '/channels/whatsapp'
      path: '/whatsapp'
      fullPath: '/channels/whatsapp'
      preLoaderRoute: typeof ChannelsWhatsappRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/channels/sms': {
      id: '/channels/sms'
      path: '/sms'
      fullPath: '/channels/sms'
      preLoaderRoute: typeof ChannelsSmsRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/channels/rcs': {
      id: '/channels/rcs'
      path: '/rcs'
      fullPath: '/channels/rcs'
      preLoaderRoute: typeof ChannelsRcsRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/campaigns/versions/$id': {
      id: '/campaigns/versions/$id'
      path: '/versions/$id'
      fullPath: '/campaigns/versions/$id'
      preLoaderRoute: typeof CampaignsVersionsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/agents/tools/new': {
      id: '/agents/tools/new'
      path: '/tools/new'
      fullPath: '/agents/tools/new'
      preLoaderRoute: typeof AgentsToolsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/channels/whatsapp_/freeform/$id': {
      id: '/channels/whatsapp_/freeform/$id'
      path: '/whatsapp/freeform/$id'
      fullPath: '/channels/whatsapp/freeform/$id'
      preLoaderRoute: typeof ChannelsWhatsappFreeformIdRouteImport
      parentRoute: typeof ChannelsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentsToolsNewRoute: typeof AgentsToolsNewRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AgentsToolsNewRoute: AgentsToolsNewRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CampaignsVersionsIdRoute: typeof CampaignsVersionsIdRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CampaignsVersionsIdRoute: CampaignsVersionsIdRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface ChannelsRouteChildren {
  ChannelsRcsRoute: typeof ChannelsRcsRoute
  ChannelsSmsRoute: typeof ChannelsSmsRoute
  ChannelsWhatsappRoute: typeof ChannelsWhatsappRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  ChannelsWhatsappFreeformIdRoute: typeof ChannelsWhatsappFreeformIdRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsRcsRoute: ChannelsRcsRoute,
  ChannelsSmsRoute: ChannelsSmsRoute,
  ChannelsWhatsappRoute: ChannelsWhatsappRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  ChannelsWhatsappFreeformIdRoute: ChannelsWhatsappFreeformIdRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ChannelsRoute: ChannelsRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  InboxIdRoute: InboxIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
